f=open("shaders/gbuffer.frag","w",encoding="utf-8") 
f.write("#version 410 core\n") 
f.write("in vec2 v_uv;\nin vec3 v_albedo;\nin vec3 v_emission;\nin float v_emission_str;\nin float v_age;\nflat in int v_type;\n") 
f.write("layout(location=0) out vec4 gAlbedoMetallic;\n") 
f.write("layout(location=1) out vec4 gNormalRoughness;\n") 
f.write("layout(location=2) out vec4 gEmission;\n") 
f.write("layout(location=3) out vec4 gPositionDepth;\n") 
f.write("uniform float u_time;\n") 
f.write("void main(){\n") 
f.write("vec2 uv=v_uv*2.0-1.0;\nfloat d=length(uv);\nif(d>1.0)discard;\n") 
f.write("float alpha=pow(1.0-d,1.4);\n") 
f.write("vec3 core=mix(v_albedo,vec3(1.0),(1.0-d)*0.5);\n") 
f.write("vec3 emission=v_emission*v_emission_str*(1.0-d*0.5);\n") 
f.write("gAlbedoMetallic=vec4(core,0.0);\n") 
f.write("gNormalRoughness=vec4(0.5,0.5,1.0,0.5);\n") 
f.write("gEmission=vec4(emission,alpha);\n") 
f.write("gPositionDepth=vec4(0.0,0.0,0.0,0.5);\n") 
f.write("}\n") 
f.close() 
print("done") 
